stages:
  download:
    cmd: stages/01_download.sh
    deps:
      - stages/01_download.sh
      - R/download.R
    outs:
      - download/Loinc.zip
  unzip:
    cmd: stages/02_unzip.sh
    deps:
      - stages/02_unzip.sh
      - download/Loinc.zip
    outs:
      - raw
  process:
    cmd: stages/03_build.sh
    deps:
      - stages/03_build.sh
      - R/process.R
    outs:
      # stages/03_build.sh filelist
      ## {{{
      - brick/AccessoryFiles/AnswerFile/AnswerList.parquet
      - brick/AccessoryFiles/AnswerFile/LoincAnswerListLink.parquet
      - brick/AccessoryFiles/ChangeSnapshot/LoincChangeSnapshot.parquet
      - brick/AccessoryFiles/ChangeSnapshot/PartChangeSnapshot.parquet
      - brick/AccessoryFiles/ComponentHierarchyBySystem/ComponentHierarchyBySystem.parquet
      - brick/AccessoryFiles/ConsumerName/ConsumerName.parquet
      - brick/AccessoryFiles/DocumentOntology/DocumentOntology.parquet
      - brick/AccessoryFiles/GroupFile/GroupAttributes.parquet
      - brick/AccessoryFiles/GroupFile/GroupLoincTerms.parquet
      - brick/AccessoryFiles/GroupFile/Group.parquet
      - brick/AccessoryFiles/GroupFile/ParentGroupAttributes.parquet
      - brick/AccessoryFiles/GroupFile/ParentGroup.parquet
      - brick/AccessoryFiles/ImagingDocuments/ImagingDocumentCodes.parquet
      - brick/AccessoryFiles/LinguisticVariants/arJO32LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/csCZ33LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/deAT24LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/deDE15LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/elGR17LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/esAR7LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/esES12LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/esMX28LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/etEE10LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/frBE23LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/frCA8LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/frFR18LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/itIT16LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/koKR13LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/LinguisticVariants.parquet
      - brick/AccessoryFiles/LinguisticVariants/nlNL22LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/plPL29LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/ptBR11LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/ruRU20LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/trTR19LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/ukUA30LinguisticVariant.parquet
      - brick/AccessoryFiles/LinguisticVariants/zhCN5LinguisticVariant.parquet
      - brick/AccessoryFiles/LoincIeeeMedicalDeviceCodeMappingTable/LoincIeeeMedicalDeviceCodeMappingTable.parquet
      - brick/AccessoryFiles/LoincRsnaRadiologyPlaybook/LoincRsnaRadiologyPlaybook.parquet
      - brick/AccessoryFiles/LoincUniversalLabOrdersValueSet/LoincUniversalLabOrdersValueSet.parquet
      - brick/AccessoryFiles/PanelsAndForms/AnswerList.parquet
      - brick/AccessoryFiles/PanelsAndForms/LoincAnswerListLink.parquet
      - brick/AccessoryFiles/PanelsAndForms/Loinc.parquet
      - brick/AccessoryFiles/PanelsAndForms/PanelsAndForms.parquet
      - brick/AccessoryFiles/PartFile/LoincPartLink_Primary.parquet
      - brick/AccessoryFiles/PartFile/LoincPartLink_Supplementary.parquet
      - brick/AccessoryFiles/PartFile/Part.parquet
      - brick/AccessoryFiles/PartFile/PartRelatedCodeMapping.parquet
      - brick/AccessoryFiles/Updates/UpdatesAdditionalFields.parquet
      - brick/AccessoryFiles/Updates/Updates.parquet
      - brick/LoincTableCore/LoincTableCore.parquet
      - brick/LoincTableCore/MapTo.parquet
      - brick/LoincTable/Loinc.parquet
      - brick/LoincTable/MapTo.parquet
      - brick/LoincTable/SourceOrganization.parquet
      ## }}}
  process-non-csv:
    cmd: stages/04_build-non-csv.sh
    deps:
      - stages/04_build-non-csv.sh
    outs:
      # stages/04_build-non-csv.sh filelist
      ## {{{
      - brick/AccessoryFiles/DocumentOntologyOwl/DocumentOntology.owl
      - brick/loinc.xml
      ## }}}
