stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - download/Loinc.zip
  unzip:
    cmd: mkdir -p "raw"; unzip download/Loinc.zip -d raw/
    deps:
      - download/Loinc.zip
    outs:
      - raw
  process:
    cmd: Rscript R/process.R
    deps:
      - R/process.R
    outs:
      # ( export IN='raw' OUT='brick'; find $IN -name '*.csv' | perl -pe 's|^\Q$ENV{IN}\E|$ENV{OUT}|;s|\.csv$|.parquet|; $_ = sprintf("%6s- %s", " ", $_)' | sort )
      - brick/Loinc.parquet
      - brick/MapTo.parquet
