stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - download/Loinc.zip
  unzip:
    cmd: mkdir -p "raw"; unzip download/Loinc.zip -d raw/
    deps:
      - download/Loinc.zip
    outs:
      - raw
  process:
    cmd: Rscript R/process.R
    deps:
      - R/process.R
    outs:
      - brick/Loinc.parquet
      - brick/MapTo.parquet
